Lazy Search
MiniDOM/MiniDOM pull request #15
Opened 2021-09-30 11:45 UTC by jvisenti

For large documents it can be necessary to terminate search early and/or filter out entire subtrees from the search.

2021-09-30 14:18 UTC, pwc3 requested changes
This looks great. Would it be possible to get some unit test coverage on this?

2021-10-01 10:07 UTC, jvisenti commented
@pwc3 Added some tests

2021-10-11 12:37 UTC, jvisenti commented
@pwc3 Is this good to merge?

2021-10-22 16:14 UTC, pwc3 approved these changes

2021-10-22 16:16 UTC, pwc3 commented
Good to merge whenever you're ready

2021-10-26 08:56 UTC, merged